defaults:
  - _task_base
  - _self_

name: real_peg_insertion_vis

image_shape: [3, 256, 256]
image_resize_shape: null   # square source; no encoder-side resize
dataset_path: data/peg_hole_tac

shape_meta:
  # acceptable types: rgb, low_dim
  obs:
    rgb:
      shape: ${task.image_shape}
      type: rgb
    eef_state:
      shape: [9]
      type: low_dim
  action:
    shape: [9] # (3+6) (x, y, z, 6d rotation)
