
name: real_peg_insertion_vis

image_shape: [3, 256, 256]
image_resize_shape: null   # square source; no encoder-side resize
dataset_path: data/peg_hole_tac

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    rgb:
      shape: ${task.image_shape}
      type: rgb
    eef_state:
      shape: [9]
      type: low_dim
  action:
    shape: [9] # (3+6) (x, y, z, 6d rotation)

dataset:
  _target_: trainflow.dataset.real_image_tactile_dataset.RealImageTactileDataset
  shape_meta: *shape_meta
  dataset_path: ${task.dataset_path}
  horizon: ${horizon}
  pad_before: ${eval:'${dataset_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  n_latency_steps: ${n_latency_steps}
  seed: 42
  val_ratio: 0.1
  max_train_episodes: null
  delta_action: False
  relative_action: False
